use std::fmt::Write as FmtWrite;
use std::path::Path;

use crate::topology::TestScenario;

/// Generate a `docker-compose.yml` string for the given scenario.
///
/// Pure function — no I/O. All paths in the output are absolute.
///
/// # Arguments
///
/// * `scenario` — parsed test scenario
/// * `base_dir` — absolute path to tempdir containing per-node config/storage
/// * `repo_root` — absolute path to the leviculum repository root
pub fn generate_compose(
    scenario: &TestScenario,
    run_id: u32,
    base_dir: &Path,
    repo_root: &Path,
) -> String {
    let test_name = &scenario.test.name;
    let integ_dir = repo_root.join("reticulum-integ");
    let lrnsd_path = repo_root.join("target/release/lrnsd");
    let lrns_path = repo_root.join("target/release/lrns");
    let vendor_path = repo_root.join("vendor/Reticulum");

    let mut out = String::new();
    writeln!(out, "# Auto-generated by reticulum-integ").ok();
    writeln!(out, "services:").ok();

    for (name, node) in &scenario.nodes {
        let node_dir = base_dir.join(name);

        writeln!(out, "  {name}:").ok();
        writeln!(out, "    build:").ok();
        writeln!(out, "      context: {}", integ_dir.display()).ok();
        writeln!(out, "    image: reticulum-test").ok();
        writeln!(out, "    container_name: integ-{test_name}-{run_id}-{name}").ok();
        writeln!(out, "    environment:").ok();
        writeln!(out, "      NODE_TYPE: {}", node.node_type).ok();
        writeln!(out, "    cap_add:").ok();
        writeln!(out, "      - NET_ADMIN").ok();
        writeln!(out, "    volumes:").ok();
        writeln!(
            out,
            "      - {}:/usr/local/bin/lrnsd:ro",
            lrnsd_path.display()
        )
        .ok();
        writeln!(
            out,
            "      - {}:/usr/local/bin/lrns:ro",
            lrns_path.display()
        )
        .ok();
        writeln!(
            out,
            "      - {}:/opt/vendor/Reticulum:ro",
            vendor_path.display()
        )
        .ok();
        writeln!(
            out,
            "      - {}:/root/.reticulum/config:ro",
            node_dir.join("config").display()
        )
        .ok();
        writeln!(
            out,
            "      - {}:/root/.reticulum/storage",
            node_dir.join("storage").display()
        )
        .ok();
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::topology::{generate_node_configs, parse_scenario};
    use std::fs;
    use std::path::PathBuf;
    use tempfile::TempDir;

    fn load_basic_probe() -> TestScenario {
        let toml_str = fs::read_to_string(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/basic_probe.toml"
        ))
        .expect("basic_probe.toml not found");
        parse_scenario(&toml_str).expect("parse failed")
    }

    fn sample_paths() -> (PathBuf, PathBuf) {
        (
            PathBuf::from("/tmp/test-nodes"),
            PathBuf::from("/home/user/leviculum"),
        )
    }

    #[test]
    fn basic_probe_has_both_services() {
        let scenario = load_basic_probe();
        let (base_dir, repo_root) = sample_paths();
        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root);

        assert!(yaml.contains("\n  alice:\n"), "missing alice service block");
        assert!(yaml.contains("\n  bob:\n"), "missing bob service block");
    }

    #[test]
    fn node_type_environment_correct() {
        let scenario = load_basic_probe();
        let (base_dir, repo_root) = sample_paths();
        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root);

        // Split into per-service blocks to check each independently.
        let alice_idx = yaml.find("  alice:").expect("no alice");
        let bob_idx = yaml.find("  bob:").expect("no bob");

        let (alice_block, bob_block) = if alice_idx < bob_idx {
            (&yaml[alice_idx..bob_idx], &yaml[bob_idx..])
        } else {
            (&yaml[bob_idx..alice_idx], &yaml[alice_idx..])
        };

        assert!(
            alice_block.contains("NODE_TYPE: rust"),
            "alice should be rust"
        );
        assert!(
            bob_block.contains("NODE_TYPE: python"),
            "bob should be python"
        );
    }

    #[test]
    fn volume_mounts_present() {
        let scenario = load_basic_probe();
        let (base_dir, repo_root) = sample_paths();
        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root);

        for node in ["alice", "bob"] {
            let node_dir = base_dir.join(node);
            assert!(
                yaml.contains(&format!(
                    "{}/target/release/lrnsd:/usr/local/bin/lrnsd:ro",
                    repo_root.display()
                )),
                "{node}: missing lrnsd volume"
            );
            assert!(
                yaml.contains(&format!(
                    "{}/target/release/lrns:/usr/local/bin/lrns:ro",
                    repo_root.display()
                )),
                "{node}: missing lrns volume"
            );
            assert!(
                yaml.contains(&format!(
                    "{}/vendor/Reticulum:/opt/vendor/Reticulum:ro",
                    repo_root.display()
                )),
                "{node}: missing vendor volume"
            );
            assert!(
                yaml.contains(&format!(
                    "{}:/root/.reticulum/config:ro",
                    node_dir.join("config").display()
                )),
                "{node}: missing config volume"
            );
            assert!(
                yaml.contains(&format!(
                    "{}:/root/.reticulum/storage",
                    node_dir.join("storage").display()
                )),
                "{node}: missing storage volume"
            );
        }
    }

    #[test]
    fn build_context_points_to_integ_dir() {
        let scenario = load_basic_probe();
        let (base_dir, repo_root) = sample_paths();
        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root);

        let expected = format!("context: {}/reticulum-integ", repo_root.display());
        assert!(
            yaml.contains(&expected),
            "build context should point to reticulum-integ dir"
        );
    }

    #[test]
    fn container_names_include_test_name() {
        let scenario = load_basic_probe();
        let (base_dir, repo_root) = sample_paths();
        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root);

        assert!(
            yaml.contains("container_name: integ-basic_probe-0-alice"),
            "missing alice container name"
        );
        assert!(
            yaml.contains("container_name: integ-basic_probe-0-bob"),
            "missing bob container name"
        );
    }

    #[test]
    fn three_node_relay_has_three_services() {
        let toml_str = r#"
[test]
name = "relay_test"

[nodes.alice]
type = "rust"
respond_to_probes = true

[nodes.relay]
type = "python"
respond_to_probes = false

[nodes.bob]
type = "rust"
respond_to_probes = true

[links]
alice-relay = "tcp"
bob-relay = "tcp"

[[steps]]
action = "sleep"
duration_secs = 5
"#;
        let scenario = parse_scenario(toml_str).expect("parse failed");
        let (base_dir, repo_root) = sample_paths();
        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root);

        assert!(yaml.contains("\n  alice:\n"), "missing alice");
        assert!(yaml.contains("\n  bob:\n"), "missing bob");
        assert!(yaml.contains("\n  relay:\n"), "missing relay");
    }

    #[test]
    fn no_ports_or_networks_sections() {
        let scenario = load_basic_probe();
        let (base_dir, repo_root) = sample_paths();
        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root);

        assert!(!yaml.contains("ports:"), "should not contain ports:");
        assert!(!yaml.contains("networks:"), "should not contain networks:");
    }

    #[test]
    fn docker_compose_config_validates() {
        let scenario = load_basic_probe();
        let tmp = TempDir::new().unwrap();
        let base_dir = tmp.path().join("nodes");
        generate_node_configs(&scenario, &base_dir).unwrap();

        // Use the real repo root (CARGO_MANIFEST_DIR is reticulum-integ/).
        let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("no parent")
            .to_path_buf();

        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root);
        let compose_file = tmp.path().join("docker-compose.yml");
        fs::write(&compose_file, &yaml).unwrap();

        let output = std::process::Command::new("docker")
            .args(["compose", "-f", compose_file.to_str().unwrap(), "config"])
            .output()
            .expect("failed to run docker compose");

        assert!(
            output.status.success(),
            "docker compose config failed:\n{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
