use std::collections::BTreeMap;
use std::fmt::Write as FmtWrite;
use std::path::{Path, PathBuf};

use crate::topology::TestScenario;

/// Generate a `docker-compose.yml` string for the given scenario.
///
/// Pure function — no I/O. All paths in the output are absolute.
///
/// # Arguments
///
/// * `scenario` — parsed test scenario
/// * `run_id` — unique run identifier for container naming
/// * `base_dir` — absolute path to tempdir containing per-node config/storage
/// * `repo_root` — absolute path to the leviculum repository root
/// * `proxy_devices` — for nodes with `rnode_proxy`, maps node name to the PTY
///   slave device path that should be mounted instead of the raw serial device
pub fn generate_compose(
    scenario: &TestScenario,
    run_id: u32,
    base_dir: &Path,
    repo_root: &Path,
    proxy_devices: &BTreeMap<String, PathBuf>,
) -> String {
    let test_name = &scenario.test.name;
    let lnsd_path = repo_root.join("target/release/lnsd");
    let lns_path = repo_root.join("target/release/lns");
    let lncp_path = repo_root.join("target/release/lncp");

    let mut out = String::new();
    writeln!(out, "# Auto-generated by reticulum-integ").ok();
    writeln!(out, "services:").ok();

    for (name, node) in &scenario.nodes {
        let node_dir = base_dir.join(name);

        writeln!(out, "  {name}:").ok();
        writeln!(out, "    build:").ok();
        writeln!(out, "      context: {}", repo_root.display()).ok();
        writeln!(out, "      dockerfile: reticulum-integ/Dockerfile").ok();
        writeln!(out, "    image: reticulum-test").ok();
        writeln!(out, "    container_name: integ-{test_name}-{run_id}-{name}").ok();
        let rust_log = scenario.test.rust_log.as_deref().unwrap_or("debug");
        writeln!(out, "    environment:").ok();
        writeln!(out, "      NODE_TYPE: {}", node.node_type).ok();
        writeln!(out, "      RUST_LOG: {rust_log}").ok();
        writeln!(out, "    cap_add:").ok();
        writeln!(out, "      - NET_ADMIN").ok();
        writeln!(out, "    volumes:").ok();
        writeln!(
            out,
            "      - {}:/usr/local/bin/lnsd:ro",
            lnsd_path.display()
        )
        .ok();
        writeln!(out, "      - {}:/usr/local/bin/lns:ro", lns_path.display()).ok();
        writeln!(
            out,
            "      - {}:/usr/local/bin/lncp:ro",
            lncp_path.display()
        )
        .ok();
        writeln!(
            out,
            "      - {}:/root/.reticulum/config:ro",
            node_dir.join("config").display()
        )
        .ok();
        writeln!(
            out,
            "      - {}:/root/.reticulum/storage",
            node_dir.join("storage").display()
        )
        .ok();

        if let Some(device) = &node.rnode {
            if let Some(pty_path) = proxy_devices.get(name) {
                // Proxy node: bind-mount PTY slave to /dev/rnode_proxy via
                // volumes (not devices) to ensure it works in privileged mode.
                // The node config uses /dev/rnode_proxy as the serial port path.
                writeln!(out, "      - \"{}:/dev/rnode_proxy\"", pty_path.display()).ok();
            }
            writeln!(out, "    privileged: true").ok();
            if proxy_devices.get(name).is_none() {
                writeln!(out, "    devices:").ok();
                writeln!(out, "      - \"{device}:{device}\"").ok();
            }
        } else if let Some(ref interfaces) = node.rnode_interfaces {
            // Multi-interface: pass through all RNode devices.
            writeln!(out, "    privileged: true").ok();
            writeln!(out, "    devices:").ok();
            for iface in interfaces {
                writeln!(out, "      - \"{}:{}\"", iface.rnode, iface.rnode).ok();
            }
        }

        if let Some(device) = &node.serial {
            // Serial LNode (e.g., T114): pass device into container.
            // If rnode already set privileged+devices, this adds the serial device.
            if node.rnode.is_none() && node.rnode_interfaces.is_none() {
                writeln!(out, "    privileged: true").ok();
                writeln!(out, "    devices:").ok();
            }
            writeln!(out, "      - \"{device}:{device}\"").ok();
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::topology::{generate_node_configs, parse_scenario};
    use std::fs;
    use std::path::PathBuf;
    use tempfile::TempDir;

    fn load_basic_probe() -> TestScenario {
        let toml_str = fs::read_to_string(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/basic_probe.toml"
        ))
        .expect("basic_probe.toml not found");
        parse_scenario(&toml_str).expect("parse failed")
    }

    fn sample_paths() -> (PathBuf, PathBuf) {
        (
            PathBuf::from("/tmp/test-nodes"),
            PathBuf::from("/home/user/leviculum"),
        )
    }

    #[test]
    fn basic_probe_has_both_services() {
        let scenario = load_basic_probe();
        let (base_dir, repo_root) = sample_paths();
        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root, &BTreeMap::new());

        assert!(yaml.contains("\n  alice:\n"), "missing alice service block");
        assert!(yaml.contains("\n  bob:\n"), "missing bob service block");
    }

    #[test]
    fn node_type_environment_correct() {
        let scenario = load_basic_probe();
        let (base_dir, repo_root) = sample_paths();
        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root, &BTreeMap::new());

        // Split into per-service blocks to check each independently.
        let alice_idx = yaml.find("  alice:").expect("no alice");
        let bob_idx = yaml.find("  bob:").expect("no bob");

        let (alice_block, bob_block) = if alice_idx < bob_idx {
            (&yaml[alice_idx..bob_idx], &yaml[bob_idx..])
        } else {
            (&yaml[bob_idx..alice_idx], &yaml[alice_idx..])
        };

        assert!(
            alice_block.contains("NODE_TYPE: rust"),
            "alice should be rust"
        );
        assert!(
            bob_block.contains("NODE_TYPE: python"),
            "bob should be python"
        );
    }

    #[test]
    fn volume_mounts_present() {
        let scenario = load_basic_probe();
        let (base_dir, repo_root) = sample_paths();
        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root, &BTreeMap::new());

        for node in ["alice", "bob"] {
            let node_dir = base_dir.join(node);
            assert!(
                yaml.contains(&format!(
                    "{}/target/release/lnsd:/usr/local/bin/lnsd:ro",
                    repo_root.display()
                )),
                "{node}: missing lnsd volume"
            );
            assert!(
                yaml.contains(&format!(
                    "{}/target/release/lns:/usr/local/bin/lns:ro",
                    repo_root.display()
                )),
                "{node}: missing lns volume"
            );
            assert!(
                yaml.contains(&format!(
                    "{}/target/release/lncp:/usr/local/bin/lncp:ro",
                    repo_root.display()
                )),
                "{node}: missing lncp volume"
            );
            assert!(
                yaml.contains(&format!(
                    "{}:/root/.reticulum/config:ro",
                    node_dir.join("config").display()
                )),
                "{node}: missing config volume"
            );
            assert!(
                yaml.contains(&format!(
                    "{}:/root/.reticulum/storage",
                    node_dir.join("storage").display()
                )),
                "{node}: missing storage volume"
            );
        }
    }

    #[test]
    fn build_context_points_to_repo_root() {
        let scenario = load_basic_probe();
        let (base_dir, repo_root) = sample_paths();
        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root, &BTreeMap::new());

        let expected = format!("context: {}", repo_root.display());
        assert!(
            yaml.contains(&expected),
            "build context should point to repo root"
        );
        assert!(
            yaml.contains("dockerfile: reticulum-integ/Dockerfile"),
            "dockerfile path should be relative to repo root"
        );
    }

    #[test]
    fn container_names_include_test_name() {
        let scenario = load_basic_probe();
        let (base_dir, repo_root) = sample_paths();
        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root, &BTreeMap::new());

        assert!(
            yaml.contains("container_name: integ-basic_probe-0-alice"),
            "missing alice container name"
        );
        assert!(
            yaml.contains("container_name: integ-basic_probe-0-bob"),
            "missing bob container name"
        );
    }

    #[test]
    fn three_node_relay_has_three_services() {
        let toml_str = r#"
[test]
name = "relay_test"

[nodes.alice]
type = "rust"
respond_to_probes = true

[nodes.relay]
type = "python"
respond_to_probes = false

[nodes.bob]
type = "rust"
respond_to_probes = true

[links]
alice-relay = "tcp"
bob-relay = "tcp"

[[steps]]
action = "sleep"
duration_secs = 5
"#;
        let scenario = parse_scenario(toml_str).expect("parse failed");
        let (base_dir, repo_root) = sample_paths();
        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root, &BTreeMap::new());

        assert!(yaml.contains("\n  alice:\n"), "missing alice");
        assert!(yaml.contains("\n  bob:\n"), "missing bob");
        assert!(yaml.contains("\n  relay:\n"), "missing relay");
    }

    #[test]
    fn rnode_compose_has_device_and_privileged() {
        let toml_str = r#"
[test]
name = "rnode_test"

[radio]
frequency = 868000000
bandwidth = 125000
sf = 7
cr = 5
txpower = 17

[nodes.alpha]
type = "rust"
respond_to_probes = true
rnode = "/dev/ttyACM0"

[nodes.beta]
type = "rust"
respond_to_probes = true
"#;
        let scenario = parse_scenario(toml_str).expect("parse failed");
        let (base_dir, repo_root) = sample_paths();
        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root, &BTreeMap::new());

        // alpha has rnode — should have privileged and devices
        let alpha_idx = yaml.find("  alpha:").expect("no alpha");
        let beta_idx = yaml.find("  beta:").expect("no beta");
        let alpha_block = if alpha_idx < beta_idx {
            &yaml[alpha_idx..beta_idx]
        } else {
            &yaml[alpha_idx..]
        };
        assert!(
            alpha_block.contains("privileged: true"),
            "alpha should have privileged"
        );
        assert!(
            alpha_block.contains("\"/dev/ttyACM0:/dev/ttyACM0\""),
            "alpha should have device mapping"
        );

        // beta has no rnode — should NOT have privileged or devices
        let beta_block = if beta_idx > alpha_idx {
            &yaml[beta_idx..]
        } else {
            &yaml[beta_idx..alpha_idx]
        };
        assert!(
            !beta_block.contains("privileged"),
            "beta should not have privileged"
        );
        assert!(
            !beta_block.contains("devices:"),
            "beta should not have devices"
        );
    }

    #[test]
    fn no_ports_or_networks_sections() {
        let scenario = load_basic_probe();
        let (base_dir, repo_root) = sample_paths();
        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root, &BTreeMap::new());

        assert!(!yaml.contains("ports:"), "should not contain ports:");
        assert!(!yaml.contains("networks:"), "should not contain networks:");
    }

    #[test]
    fn docker_compose_config_validates() {
        let scenario = load_basic_probe();
        let tmp = TempDir::new().unwrap();
        let base_dir = tmp.path().join("nodes");
        generate_node_configs(&scenario, &base_dir).unwrap();

        // Use the real repo root (CARGO_MANIFEST_DIR is reticulum-integ/).
        let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("no parent")
            .to_path_buf();

        let yaml = generate_compose(&scenario, 0, &base_dir, &repo_root, &BTreeMap::new());
        let compose_file = tmp.path().join("docker-compose.yml");
        fs::write(&compose_file, &yaml).unwrap();

        let output = std::process::Command::new("docker")
            .args(["compose", "-f", compose_file.to_str().unwrap(), "config"])
            .output()
            .expect("failed to run docker compose");

        assert!(
            output.status.success(),
            "docker compose config failed:\n{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
