//! Tests for BZ2 compression compatibility with Python
//!
//! These tests verify that our BZ2 implementation is compatible with Python's bz2 module.
//! Test vectors are generated by scripts/generate_bz2_vectors.py

#![cfg(feature = "compression")]

use reticulum_core::compression::{compress, decompress, decompress_auto};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct TestVectors {
    #[serde(rename = "description")]
    _description: String,
    #[serde(default, rename = "generator")]
    _generator: String,
    #[serde(default, rename = "note")]
    _note: String,
    vectors: Vec<TestVector>,
}

#[derive(Debug, Deserialize)]
struct TestVector {
    name: String,
    description: String,
    uncompressed_hex: String,
    compressed_hex: String,
}

fn load_vectors() -> TestVectors {
    let json = include_str!("vectors/bz2_vectors.json");
    serde_json::from_str(json).expect("Failed to parse bz2_vectors.json")
}

fn hex_decode(s: &str) -> Vec<u8> {
    hex::decode(s).expect("Invalid hex string")
}

/// Test that Rust can decompress data compressed by Python
#[test]
fn test_rust_decompress_python_compressed() {
    let vectors = load_vectors();

    for vector in &vectors.vectors {
        let python_compressed = hex_decode(&vector.compressed_hex);
        let expected = hex_decode(&vector.uncompressed_hex);

        // Use decompress_auto for unknown sizes
        let result = decompress_auto(&python_compressed, 1024 * 1024);

        match result {
            Ok(decompressed) => {
                assert_eq!(
                    decompressed, expected,
                    "Decompression mismatch for vector '{}': {}",
                    vector.name, vector.description
                );
            }
            Err(e) => {
                panic!(
                    "Failed to decompress vector '{}' ({}): {:?}",
                    vector.name, vector.description, e
                );
            }
        }
    }
}

/// Test that Rust can decompress with known size
#[test]
fn test_rust_decompress_with_size() {
    let vectors = load_vectors();

    for vector in &vectors.vectors {
        let python_compressed = hex_decode(&vector.compressed_hex);
        let expected = hex_decode(&vector.uncompressed_hex);

        // Skip empty test since decompressing with size 0 doesn't make sense
        if expected.is_empty() {
            continue;
        }

        // Use exact size (+ some margin for safety)
        let result = decompress(&python_compressed, expected.len() + 100);

        match result {
            Ok(decompressed) => {
                assert_eq!(
                    decompressed, expected,
                    "Decompression mismatch for vector '{}': {}",
                    vector.name, vector.description
                );
            }
            Err(e) => {
                panic!(
                    "Failed to decompress vector '{}' ({}): {:?}",
                    vector.name, vector.description, e
                );
            }
        }
    }
}

/// Test that Rust compression can be decompressed by Rust
/// (roundtrip test with our own implementation)
#[test]
fn test_rust_compress_decompress_roundtrip() {
    let vectors = load_vectors();

    for vector in &vectors.vectors {
        let original = hex_decode(&vector.uncompressed_hex);

        // Compress with Rust
        let compressed = compress(&original).unwrap_or_else(|e| {
            panic!(
                "Failed to compress vector '{}': {}: {e}",
                vector.name, vector.description
            )
        });

        // Decompress with Rust
        let decompressed = decompress_auto(&compressed, 1024 * 1024).unwrap_or_else(|e| {
            panic!(
                "Failed to decompress vector '{}': {}: {e}",
                vector.name, vector.description
            )
        });

        assert_eq!(
            decompressed, original,
            "Roundtrip mismatch for vector '{}': {}",
            vector.name, vector.description
        );
    }
}

/// Test that Rust compression produces valid BZ2 magic bytes
#[test]
fn test_rust_compression_magic() {
    let data = b"Test data for magic byte verification";
    let compressed = compress(data).expect("Compression failed");

    // BZ2 streams start with "BZ" followed by version ('h' for huffman)
    assert!(compressed.len() >= 3, "Compressed data too short");
    assert_eq!(compressed[0], b'B', "First magic byte should be 'B'");
    assert_eq!(compressed[1], b'Z', "Second magic byte should be 'Z'");
    assert_eq!(compressed[2], b'h', "Third byte should be 'h' (huffman)");
}

/// Test compression ratios on known compressible data
#[test]
fn test_compression_ratios() {
    // Highly compressible: repeated pattern
    let repeated = vec![b'A'; 1000];
    let compressed = compress(&repeated).expect("Compression failed");
    assert!(
        compressed.len() < repeated.len() / 2,
        "Repeated pattern should compress to less than half size"
    );

    // Less compressible: sequential bytes
    // Note: BZ2 has significant overhead (~40 bytes header), so small random-ish
    // data may actually expand. This is expected behavior.
    let sequential: Vec<u8> = (0..=255).collect();
    let compressed_seq = compress(&sequential).expect("Compression failed");
    // BZ2 can expand small incompressible data due to header overhead
    // Just verify it doesn't expand dramatically
    assert!(
        compressed_seq.len() <= sequential.len() * 2,
        "Sequential data shouldn't expand more than 2x"
    );
}

/// Test specific edge cases
#[test]
fn test_edge_cases() {
    // Empty data
    let empty = compress(b"").expect("Empty compression failed");
    let decompressed = decompress_auto(&empty, 1024).expect("Empty decompression failed");
    assert!(
        decompressed.is_empty(),
        "Empty data should decompress to empty"
    );

    // Single byte
    let single = compress(b"x").expect("Single byte compression failed");
    let decompressed = decompress_auto(&single, 1024).expect("Single byte decompression failed");
    assert_eq!(decompressed, b"x", "Single byte mismatch");

    // Two bytes
    let two = compress(b"ab").expect("Two byte compression failed");
    let decompressed = decompress_auto(&two, 1024).expect("Two byte decompression failed");
    assert_eq!(decompressed, b"ab", "Two byte mismatch");
}

/// Test that decompression fails gracefully on invalid data
#[test]
fn test_invalid_data() {
    use reticulum_core::compression::CompressionError;

    // Random garbage
    let garbage = b"not bz2 data at all";
    let result = decompress(garbage, 1024);
    assert!(matches!(result, Err(CompressionError::InvalidMagic)));

    // Truncated BZ2 header
    let truncated = b"BZh9";
    let result = decompress(truncated, 1024);
    assert!(result.is_err(), "Truncated data should fail");

    // Valid header but corrupt data
    let corrupt = b"BZh91AY&SY\x00\x00\x00\x00";
    let result = decompress(corrupt, 1024);
    assert!(result.is_err(), "Corrupt data should fail");
}
