//! Tests against Python Reticulum test vectors
//!
//! This module loads test_vectors.json generated by the Python script
//! and verifies that our Rust implementation produces identical outputs.

// Fields in vector structs are loaded from JSON; some are for future tests
#![allow(dead_code)]

use reticulum_core::crypto::{decrypt_token, derive_key, encrypt_token, full_hash, truncated_hash};
use reticulum_core::identity::Identity;
use serde::Deserialize;
use std::fs;

#[derive(Debug, Deserialize)]
struct TestVectors {
    identity: IdentityVectors,
    signing: SigningVectors,
    hkdf: HkdfVectors,
    hkdf_no_context: HkdfNoContextVectors,
    token: TokenVectors,
    identity_encrypt: IdentityEncryptVectors,
    destination: DestinationVectors,
    packet_flags: Vec<PacketFlagsVectors>,
    packets: Vec<PacketVectors>,
    link_request: LinkRequestVectors,
    link_id: LinkIdVectors,
    announce: AnnounceVectors,
    announce_no_app_data: AnnounceNoAppDataVectors,
    link_proof: LinkProofVectors,
    ifac: IfacVectors,
    ifac_netname_only: IfacNetnameOnlyVectors,
}

#[derive(Debug, Deserialize)]
struct IfacVectors {
    netname: String,
    netkey: String,
    ifac_size: usize,
    ifac_salt: String,
    netname_hash: String,
    netkey_hash: String,
    ifac_origin: String,
    ifac_origin_hash: String,
    ifac_key: String,
    ifac_identity_hash: String,
    test_packet: String,
    signature: String,
    ifac_value: String,
    mask: String,
    masked_packet: String,
}

#[derive(Debug, Deserialize)]
struct IfacNetnameOnlyVectors {
    netname: String,
    ifac_origin_hash: String,
    ifac_key: String,
}

#[derive(Debug, Deserialize)]
struct IdentityVectors {
    private_key: String,
    public_key: String,
    hash: String,
}

#[derive(Debug, Deserialize)]
struct SigningVectors {
    message: String,
    signature: String,
}

#[derive(Debug, Deserialize)]
struct HkdfVectors {
    ikm: String,
    salt: String,
    info: String,
    length: usize,
    output: String,
}

#[derive(Debug, Deserialize)]
struct HkdfNoContextVectors {
    ikm: String,
    salt: String,
    length: usize,
    output: String,
}

#[derive(Debug, Deserialize)]
struct TokenVectors {
    key: String,
    iv: String,
    plaintext: String,
    ciphertext: String,
    token: String,
}

#[derive(Debug, Deserialize)]
struct IdentityEncryptVectors {
    identity_public_key: String,
    identity_hash: String,
    ephemeral_private_key: String,
    ephemeral_public_key: String,
    shared_key: String,
    derived_key: String,
    plaintext: String,
    iv: String,
    token_ciphertext: String,
    full_ciphertext: String,
}

#[derive(Debug, Deserialize)]
struct DestinationVectors {
    app_name: String,
    aspects: Vec<String>,
    full_name: String,
    name_hash: String,
    identity_hash: String,
    destination_hash: String,
}

#[derive(Debug, Deserialize)]
struct PacketFlagsVectors {
    name: String,
    header_type: u8,
    context_flag: u8,
    transport_type: u8,
    dest_type: u8,
    packet_type: u8,
    expected_flags: u8,
}

#[derive(Debug, Deserialize)]
struct PacketVectors {
    name: String,
    flags: u8,
    hops: u8,
    header_type: u8,
    #[serde(default)]
    transport_id: Option<String>,
    dest_hash: String,
    context: u8,
    data: String,
    raw_packet: String,
}

#[derive(Debug, Deserialize)]
struct LinkRequestVectors {
    ephemeral_private_key: String,
    ephemeral_public_key: String,
    signing_seed: String,
    verifying_public_key: String,
    request_data: String,
}

#[derive(Debug, Deserialize)]
struct LinkIdVectors {
    raw_packet: String,
    hashable_part: String,
    link_id: String,
}

#[derive(Debug, Deserialize)]
struct AnnounceVectors {
    app_name: String,
    aspects: Vec<String>,
    full_name: String,
    name_hash: String,
    random_hash: String,
    identity_hash: String,
    destination_hash: String,
    public_key: String,
    signed_data: String,
    signature: String,
    app_data: String,
    payload: String,
}

#[derive(Debug, Deserialize)]
struct AnnounceNoAppDataVectors {
    destination_hash: String,
    signed_data: String,
    signature: String,
    payload: String,
}

#[derive(Debug, Deserialize)]
struct LinkProofVectors {
    link_id: String,
    initiator_x25519_private: String,
    initiator_x25519_public: String,
    initiator_ed25519_seed: String,
    initiator_ed25519_public: String,
    responder_x25519_private: String,
    responder_x25519_public: String,
    responder_signing_public: String,
    signalling_bytes: String,
    signed_data: String,
    signature: String,
    proof_payload: String,
    shared_key: String,
    derived_key: String,
}

fn load_vectors() -> TestVectors {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../tests/vectors/test_vectors.json"
    );
    let content = fs::read_to_string(path).expect("Failed to read test vectors");
    serde_json::from_str(&content).expect("Failed to parse test vectors")
}

#[test]
fn test_identity_from_private_key() {
    let vectors = load_vectors();

    let private_key = hex::decode(&vectors.identity.private_key).unwrap();
    let expected_public = hex::decode(&vectors.identity.public_key).unwrap();
    let expected_hash = hex::decode(&vectors.identity.hash).unwrap();

    let identity = Identity::from_private_key_bytes(&private_key).unwrap();

    assert_eq!(
        identity.public_key_bytes().to_vec(),
        expected_public,
        "Public key mismatch"
    );
    assert_eq!(
        identity.hash().to_vec(),
        expected_hash,
        "Identity hash mismatch"
    );
}

#[test]
fn test_identity_signing() {
    let vectors = load_vectors();

    let private_key = hex::decode(&vectors.identity.private_key).unwrap();
    let message = hex::decode(&vectors.signing.message).unwrap();
    let expected_signature = hex::decode(&vectors.signing.signature).unwrap();

    let identity = Identity::from_private_key_bytes(&private_key).unwrap();
    let signature = identity.sign(&message).unwrap();

    assert_eq!(signature.to_vec(), expected_signature, "Signature mismatch");

    // Verify signature works
    assert!(identity.verify(&message, &signature).unwrap());
}

#[test]
fn test_hkdf_with_context() {
    let vectors = load_vectors();

    let ikm = hex::decode(&vectors.hkdf.ikm).unwrap();
    let salt = hex::decode(&vectors.hkdf.salt).unwrap();
    let info = hex::decode(&vectors.hkdf.info).unwrap();
    let expected = hex::decode(&vectors.hkdf.output).unwrap();

    let mut output = vec![0u8; vectors.hkdf.length];
    derive_key(&ikm, Some(&salt), Some(&info), &mut output);

    assert_eq!(output, expected, "HKDF with context output mismatch");
}

#[test]
fn test_hkdf_no_context() {
    let vectors = load_vectors();

    let ikm = hex::decode(&vectors.hkdf_no_context.ikm).unwrap();
    let salt = hex::decode(&vectors.hkdf_no_context.salt).unwrap();
    let expected = hex::decode(&vectors.hkdf_no_context.output).unwrap();

    let mut output = vec![0u8; vectors.hkdf_no_context.length];
    derive_key(&ikm, Some(&salt), None, &mut output);

    assert_eq!(output, expected, "HKDF without context output mismatch");
}

#[test]
fn test_token_encryption() {
    let vectors = load_vectors();

    let key = hex::decode(&vectors.token.key).unwrap();
    let iv = hex::decode(&vectors.token.iv).unwrap();
    let plaintext = hex::decode(&vectors.token.plaintext).unwrap();
    let expected_token = hex::decode(&vectors.token.token).unwrap();

    // Calculate buffer size: IV (16) + padded ciphertext + HMAC (32)
    let padded_len = ((plaintext.len() / 16) + 1) * 16;
    let mut token = vec![0u8; 16 + padded_len + 32];

    let iv_arr: [u8; 16] = iv.try_into().unwrap();
    let token_len = encrypt_token(&key, &iv_arr, &plaintext, &mut token).unwrap();
    token.truncate(token_len);

    assert_eq!(token, expected_token, "Token encryption mismatch");
}

#[test]
fn test_token_decryption() {
    let vectors = load_vectors();

    let key = hex::decode(&vectors.token.key).unwrap();
    let token = hex::decode(&vectors.token.token).unwrap();
    let expected_plaintext = hex::decode(&vectors.token.plaintext).unwrap();

    let mut plaintext = vec![0u8; token.len()];
    let plaintext_len = decrypt_token(&key, &token, &mut plaintext).unwrap();
    plaintext.truncate(plaintext_len);

    assert_eq!(plaintext, expected_plaintext, "Token decryption mismatch");
}

#[test]
fn test_identity_encrypt_deterministic() {
    let vectors = load_vectors();

    let private_key = hex::decode(&vectors.identity.private_key).unwrap();
    let ephemeral_private = hex::decode(&vectors.identity_encrypt.ephemeral_private_key).unwrap();
    let iv = hex::decode(&vectors.identity_encrypt.iv).unwrap();
    let plaintext = hex::decode(&vectors.identity_encrypt.plaintext).unwrap();
    let expected_ciphertext = hex::decode(&vectors.identity_encrypt.full_ciphertext).unwrap();

    let identity = Identity::from_private_key_bytes(&private_key).unwrap();

    let ephemeral_arr: [u8; 32] = ephemeral_private.try_into().unwrap();
    let iv_arr: [u8; 16] = iv.try_into().unwrap();

    let ciphertext = identity
        .encrypt_with_keys(&plaintext, &ephemeral_arr, &iv_arr)
        .unwrap();

    assert_eq!(
        hex::encode(&ciphertext),
        hex::encode(&expected_ciphertext),
        "Identity encrypt mismatch\nExpected: {}\nGot:      {}",
        hex::encode(&expected_ciphertext),
        hex::encode(&ciphertext)
    );
}

#[test]
fn test_identity_decrypt() {
    let vectors = load_vectors();

    let private_key = hex::decode(&vectors.identity.private_key).unwrap();
    let ciphertext = hex::decode(&vectors.identity_encrypt.full_ciphertext).unwrap();
    let expected_plaintext = hex::decode(&vectors.identity_encrypt.plaintext).unwrap();

    let identity = Identity::from_private_key_bytes(&private_key).unwrap();
    let decrypted = identity.decrypt(&ciphertext).unwrap();

    assert_eq!(decrypted, expected_plaintext, "Identity decrypt mismatch");
}

#[test]
fn test_destination_hash() {
    let vectors = load_vectors();

    let full_name = &vectors.destination.full_name;
    let expected_name_hash = hex::decode(&vectors.destination.name_hash).unwrap();
    let identity_hash = hex::decode(&vectors.destination.identity_hash).unwrap();
    let expected_dest_hash = hex::decode(&vectors.destination.destination_hash).unwrap();

    // Name hash is first 10 bytes of full_hash
    let name_hash_full = full_hash(full_name.as_bytes());
    let name_hash = &name_hash_full[..10];

    assert_eq!(name_hash.to_vec(), expected_name_hash, "Name hash mismatch");

    // Destination hash = truncated_hash(name_hash + identity_hash)
    let mut hash_material = Vec::with_capacity(10 + 16);
    hash_material.extend_from_slice(name_hash);
    hash_material.extend_from_slice(&identity_hash);

    let dest_hash = truncated_hash(&hash_material);

    assert_eq!(
        dest_hash.to_vec(),
        expected_dest_hash,
        "Destination hash mismatch"
    );
}

#[test]
fn test_encrypt_decrypt_roundtrip() {
    use rand_core::OsRng;

    // Test that our own encrypt/decrypt roundtrips correctly
    let identity = Identity::generate(&mut OsRng);
    let plaintext = b"Hello, this is a test message for roundtrip encryption!";

    let ciphertext = identity.encrypt(plaintext, &mut OsRng).unwrap();
    let decrypted = identity.decrypt(&ciphertext).unwrap();

    assert_eq!(decrypted, plaintext);
}

// ==========================================================
// Packet serialization tests
// ==========================================================

use reticulum_core::constants::TRUNCATED_HASHBYTES;
use reticulum_core::link::Link;
use reticulum_core::packet::{
    HeaderType, Packet, PacketContext, PacketData, PacketFlags, PacketType, TransportType,
};
use reticulum_core::DestinationType;

fn load_all_vectors() -> TestVectors {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../tests/vectors/test_vectors.json"
    );
    let content = fs::read_to_string(path).expect("Failed to read test vectors");
    serde_json::from_str(&content).expect("Failed to parse test vectors")
}

#[test]
fn test_packet_flags_encoding() {
    let vectors = load_all_vectors();

    for test in &vectors.packet_flags {
        let flags = PacketFlags {
            ifac_flag: false, // Test vectors don't use IFAC
            header_type: if test.header_type == 0 {
                HeaderType::Type1
            } else {
                HeaderType::Type2
            },
            context_flag: test.context_flag != 0,
            transport_type: if test.transport_type == 0 {
                TransportType::Broadcast
            } else {
                TransportType::Transport
            },
            dest_type: DestinationType::try_from(test.dest_type).unwrap(),
            packet_type: PacketType::try_from(test.packet_type).unwrap(),
        };

        let encoded = flags.to_byte();
        assert_eq!(
            encoded, test.expected_flags,
            "Flags encoding mismatch for '{}': expected 0x{:02x}, got 0x{:02x}",
            test.name, test.expected_flags, encoded
        );
    }
}

#[test]
fn test_packet_flags_decoding() {
    let vectors = load_all_vectors();

    for test in &vectors.packet_flags {
        let decoded = PacketFlags::from_byte(test.expected_flags).unwrap();

        assert_eq!(
            decoded.header_type as u8, test.header_type,
            "Header type mismatch for '{}': expected {}, got {}",
            test.name, test.header_type, decoded.header_type as u8
        );
        assert_eq!(
            decoded.context_flag as u8, test.context_flag,
            "Context flag mismatch for '{}'",
            test.name
        );
        assert_eq!(
            decoded.transport_type as u8, test.transport_type,
            "Transport type mismatch for '{}'",
            test.name
        );
        assert_eq!(
            decoded.dest_type as u8, test.dest_type,
            "Dest type mismatch for '{}': expected {}, got {}",
            test.name, test.dest_type, decoded.dest_type as u8
        );
        assert_eq!(
            decoded.packet_type as u8, test.packet_type,
            "Packet type mismatch for '{}'",
            test.name
        );
    }
}

#[test]
fn test_packet_serialization() {
    let vectors = load_all_vectors();

    for test in &vectors.packets {
        let expected_raw = hex::decode(&test.raw_packet).unwrap();
        let dest_hash_bytes = hex::decode(&test.dest_hash).unwrap();
        let data_bytes = hex::decode(&test.data).unwrap();

        let mut dest_hash = [0u8; TRUNCATED_HASHBYTES];
        dest_hash.copy_from_slice(&dest_hash_bytes);

        let transport_id = test.transport_id.as_ref().map(|tid| {
            let bytes = hex::decode(tid).unwrap();
            let mut arr = [0u8; TRUNCATED_HASHBYTES];
            arr.copy_from_slice(&bytes);
            arr
        });

        let flags = PacketFlags::from_byte(test.flags).unwrap();
        let context = PacketContext::try_from(test.context).unwrap();

        let packet = Packet {
            flags,
            hops: test.hops,
            transport_id,
            destination_hash: dest_hash,
            context,
            data: PacketData::Owned(data_bytes),
        };

        let mut buffer = vec![0u8; 512];
        let size = packet.pack(&mut buffer).unwrap();
        buffer.truncate(size);

        assert_eq!(
            hex::encode(&buffer),
            hex::encode(&expected_raw),
            "Packet serialization mismatch for '{}'\nExpected: {}\nGot:      {}",
            test.name,
            test.raw_packet,
            hex::encode(&buffer)
        );
    }
}

#[test]
fn test_packet_deserialization() {
    let vectors = load_all_vectors();

    for test in &vectors.packets {
        let raw = hex::decode(&test.raw_packet).unwrap();
        let expected_dest_hash = hex::decode(&test.dest_hash).unwrap();
        let expected_data = hex::decode(&test.data).unwrap();

        let packet = Packet::unpack(&raw).unwrap();

        assert_eq!(
            packet.flags.to_byte(),
            test.flags,
            "Flags mismatch for '{}'",
            test.name
        );
        assert_eq!(packet.hops, test.hops, "Hops mismatch for '{}'", test.name);
        assert_eq!(
            packet.destination_hash.to_vec(),
            expected_dest_hash,
            "Dest hash mismatch for '{}'",
            test.name
        );
        assert_eq!(
            packet.context as u8, test.context,
            "Context mismatch for '{}'",
            test.name
        );
        assert_eq!(
            packet.data.as_slice(),
            &expected_data[..],
            "Data mismatch for '{}'",
            test.name
        );

        if let Some(ref expected_tid) = test.transport_id {
            let tid_bytes = hex::decode(expected_tid).unwrap();
            assert!(
                packet.transport_id.is_some(),
                "Expected transport_id for '{}'",
                test.name
            );
            assert_eq!(
                packet.transport_id.unwrap().to_vec(),
                tid_bytes,
                "Transport ID mismatch for '{}'",
                test.name
            );
        }
    }
}

#[test]
fn test_link_id_calculation() {
    let vectors = load_all_vectors();

    let raw_packet = hex::decode(&vectors.link_id.raw_packet).unwrap();
    let expected_link_id = hex::decode(&vectors.link_id.link_id).unwrap();

    let link_id = Link::calculate_link_id(&raw_packet);

    assert_eq!(
        link_id.as_bytes().to_vec(),
        expected_link_id,
        "Link ID calculation mismatch\nExpected: {}\nGot:      {}",
        vectors.link_id.link_id,
        hex::encode(link_id.as_bytes())
    );
}

// ==========================================================
// Announce tests
// ==========================================================

#[test]
fn test_announce_signature_verification() {
    let vectors = load_all_vectors();
    let private_key = hex::decode(&vectors.identity.private_key).unwrap();

    // Create identity from private key
    let identity = Identity::from_private_key_bytes(&private_key).unwrap();

    // Verify announce structure
    let public_key = hex::decode(&vectors.announce.public_key).unwrap();
    let signature = hex::decode(&vectors.announce.signature).unwrap();
    let signed_data = hex::decode(&vectors.announce.signed_data).unwrap();

    // Verify that the public key from announce matches identity
    assert_eq!(
        identity.public_key_bytes().to_vec(),
        public_key,
        "Public key mismatch"
    );

    // Verify signature using identity
    assert!(
        identity.verify(&signed_data, &signature).unwrap(),
        "Announce signature verification failed"
    );
}

#[test]
fn test_announce_destination_hash() {
    let vectors = load_all_vectors();

    // Calculate destination hash from name_hash and identity_hash
    let name_hash = hex::decode(&vectors.announce.name_hash).unwrap();
    let identity_hash = hex::decode(&vectors.announce.identity_hash).unwrap();
    let expected_dest_hash = hex::decode(&vectors.announce.destination_hash).unwrap();

    // dest_hash = truncated_hash(name_hash + identity_hash)
    let mut hash_material = Vec::new();
    hash_material.extend_from_slice(&name_hash);
    hash_material.extend_from_slice(&identity_hash);

    let dest_hash = truncated_hash(&hash_material);

    assert_eq!(
        dest_hash.to_vec(),
        expected_dest_hash,
        "Announce destination hash mismatch"
    );
}

#[test]
fn test_announce_name_hash() {
    let vectors = load_all_vectors();

    // name_hash = first 10 bytes of full_hash(full_name)
    let full_name = &vectors.announce.full_name;
    let expected_name_hash = hex::decode(&vectors.announce.name_hash).unwrap();

    let name_hash_full = full_hash(full_name.as_bytes());
    let name_hash = &name_hash_full[..10];

    assert_eq!(
        name_hash.to_vec(),
        expected_name_hash,
        "Announce name hash mismatch"
    );
}

#[test]
fn test_announce_payload_parsing() {
    let vectors = load_all_vectors();

    // Parse announce payload
    let payload = hex::decode(&vectors.announce.payload).unwrap();
    let expected_public_key = hex::decode(&vectors.announce.public_key).unwrap();
    let expected_name_hash = hex::decode(&vectors.announce.name_hash).unwrap();
    let expected_random_hash = hex::decode(&vectors.announce.random_hash).unwrap();
    let expected_signature = hex::decode(&vectors.announce.signature).unwrap();
    let expected_app_data = hex::decode(&vectors.announce.app_data).unwrap();

    // Payload format: public_key(64) + name_hash(10) + random_hash(10) + signature(64) + app_data
    assert!(payload.len() >= 148, "Announce payload too short");

    let public_key = &payload[0..64];
    let name_hash = &payload[64..74];
    let random_hash = &payload[74..84];
    let signature = &payload[84..148];
    let app_data = &payload[148..];

    assert_eq!(public_key, &expected_public_key[..], "Public key mismatch");
    assert_eq!(name_hash, &expected_name_hash[..], "Name hash mismatch");
    assert_eq!(
        random_hash,
        &expected_random_hash[..],
        "Random hash mismatch"
    );
    assert_eq!(signature, &expected_signature[..], "Signature mismatch");
    assert_eq!(app_data, &expected_app_data[..], "App data mismatch");
}

#[test]
fn test_announce_no_app_data() {
    let vectors = load_all_vectors();
    let private_key = hex::decode(&vectors.identity.private_key).unwrap();

    let identity = Identity::from_private_key_bytes(&private_key).unwrap();

    let signed_data = hex::decode(&vectors.announce_no_app_data.signed_data).unwrap();
    let signature = hex::decode(&vectors.announce_no_app_data.signature).unwrap();

    // Verify signature
    assert!(
        identity.verify(&signed_data, &signature).unwrap(),
        "Announce (no app_data) signature verification failed"
    );

    // Verify payload is exactly 148 bytes (no app_data)
    let payload = hex::decode(&vectors.announce_no_app_data.payload).unwrap();
    assert_eq!(
        payload.len(),
        148,
        "Announce without app_data should be exactly 148 bytes"
    );
}

// ==========================================================
// Link proof tests
// ==========================================================

#[test]
fn test_link_proof_signature() {
    let vectors = load_all_vectors();
    let private_key = hex::decode(&vectors.identity.private_key).unwrap();

    // The responder uses the destination's identity to sign
    let identity = Identity::from_private_key_bytes(&private_key).unwrap();

    let signed_data = hex::decode(&vectors.link_proof.signed_data).unwrap();
    let signature = hex::decode(&vectors.link_proof.signature).unwrap();

    // Verify signature
    assert!(
        identity.verify(&signed_data, &signature).unwrap(),
        "Link proof signature verification failed"
    );
}

#[test]
fn test_link_proof_payload_structure() {
    let vectors = load_all_vectors();

    let proof_payload = hex::decode(&vectors.link_proof.proof_payload).unwrap();
    let expected_signature = hex::decode(&vectors.link_proof.signature).unwrap();
    let expected_responder_pub = hex::decode(&vectors.link_proof.responder_x25519_public).unwrap();
    let expected_signalling = hex::decode(&vectors.link_proof.signalling_bytes).unwrap();

    // Proof format: signature(64) + responder_X25519_pub(32) + signalling(3) = 99 bytes
    assert_eq!(proof_payload.len(), 99, "Link proof should be 99 bytes");

    let signature = &proof_payload[0..64];
    let responder_pub = &proof_payload[64..96];
    let signalling = &proof_payload[96..99];

    assert_eq!(signature, &expected_signature[..], "Signature mismatch");
    assert_eq!(
        responder_pub,
        &expected_responder_pub[..],
        "Responder public key mismatch"
    );
    assert_eq!(
        signalling,
        &expected_signalling[..],
        "Signalling bytes mismatch"
    );
}

#[test]
fn test_link_proof_signed_data_structure() {
    let vectors = load_all_vectors();

    let signed_data = hex::decode(&vectors.link_proof.signed_data).unwrap();
    let link_id = hex::decode(&vectors.link_proof.link_id).unwrap();
    let initiator_x25519_pub = hex::decode(&vectors.link_proof.initiator_x25519_public).unwrap();
    let initiator_ed25519_pub = hex::decode(&vectors.link_proof.initiator_ed25519_public).unwrap();
    let signalling = hex::decode(&vectors.link_proof.signalling_bytes).unwrap();

    // Signed data: link_id(16) + initiator_X25519_pub(32) + initiator_Ed25519_pub(32) + signalling(3) = 83 bytes
    assert_eq!(signed_data.len(), 83, "Signed data should be 83 bytes");

    assert_eq!(
        &signed_data[0..16],
        &link_id[..],
        "Link ID mismatch in signed data"
    );
    assert_eq!(
        &signed_data[16..48],
        &initiator_x25519_pub[..],
        "Initiator X25519 pub mismatch"
    );
    assert_eq!(
        &signed_data[48..80],
        &initiator_ed25519_pub[..],
        "Initiator Ed25519 pub mismatch"
    );
    assert_eq!(
        &signed_data[80..83],
        &signalling[..],
        "Signalling mismatch in signed data"
    );
}

#[test]
fn test_link_key_derivation() {
    let vectors = load_all_vectors();

    let link_id = hex::decode(&vectors.link_proof.link_id).unwrap();
    let shared_key = hex::decode(&vectors.link_proof.shared_key).unwrap();
    let expected_derived = hex::decode(&vectors.link_proof.derived_key).unwrap();

    // Derive key using HKDF(shared_key, salt=link_id, context=None, length=64)
    let mut derived_key = [0u8; 64];
    derive_key(&shared_key, Some(&link_id), None, &mut derived_key);

    assert_eq!(
        derived_key.to_vec(),
        expected_derived,
        "Link key derivation mismatch"
    );
}

#[test]
fn test_link_ecdh_shared_key() {
    let vectors = load_all_vectors();

    let initiator_prv = hex::decode(&vectors.link_proof.initiator_x25519_private).unwrap();
    let responder_pub = hex::decode(&vectors.link_proof.responder_x25519_public).unwrap();
    let expected_shared = hex::decode(&vectors.link_proof.shared_key).unwrap();

    // Perform ECDH: initiator_private * responder_public
    let initiator_secret =
        x25519_dalek::StaticSecret::from(<[u8; 32]>::try_from(&initiator_prv[..]).unwrap());
    let responder_public =
        x25519_dalek::PublicKey::from(<[u8; 32]>::try_from(&responder_pub[..]).unwrap());

    let shared = initiator_secret.diffie_hellman(&responder_public);

    assert_eq!(
        shared.as_bytes().to_vec(),
        expected_shared,
        "ECDH shared key mismatch"
    );
}

#[test]
fn test_link_ecdh_symmetry() {
    let vectors = load_all_vectors();

    let initiator_prv = hex::decode(&vectors.link_proof.initiator_x25519_private).unwrap();
    let initiator_pub = hex::decode(&vectors.link_proof.initiator_x25519_public).unwrap();
    let responder_prv = hex::decode(&vectors.link_proof.responder_x25519_private).unwrap();
    let responder_pub = hex::decode(&vectors.link_proof.responder_x25519_public).unwrap();

    // Both sides should compute the same shared key
    let initiator_secret =
        x25519_dalek::StaticSecret::from(<[u8; 32]>::try_from(&initiator_prv[..]).unwrap());
    let responder_secret =
        x25519_dalek::StaticSecret::from(<[u8; 32]>::try_from(&responder_prv[..]).unwrap());
    let initiator_public =
        x25519_dalek::PublicKey::from(<[u8; 32]>::try_from(&initiator_pub[..]).unwrap());
    let responder_public =
        x25519_dalek::PublicKey::from(<[u8; 32]>::try_from(&responder_pub[..]).unwrap());

    let shared_from_initiator = initiator_secret.diffie_hellman(&responder_public);
    let shared_from_responder = responder_secret.diffie_hellman(&initiator_public);

    assert_eq!(
        shared_from_initiator.as_bytes(),
        shared_from_responder.as_bytes(),
        "ECDH should be symmetric"
    );
}

// ==========================================================
// IFAC (Interface Access Code) tests
// ==========================================================

use reticulum_core::ifac::IfacConfig;

#[test]
fn test_ifac_key_derivation() {
    let vectors = load_all_vectors();

    // Verify key derivation matches Python
    let config = IfacConfig::new(
        Some(&vectors.ifac.netname),
        Some(&vectors.ifac.netkey),
        vectors.ifac.ifac_size,
    )
    .unwrap();

    let expected_identity_hash = hex::decode(&vectors.ifac.ifac_identity_hash).unwrap();

    assert_eq!(
        config.identity().hash().to_vec(),
        expected_identity_hash,
        "IFAC identity hash mismatch"
    );
}

#[test]
fn test_ifac_key_derivation_netname_only() {
    let vectors = load_all_vectors();

    // Test with netname only
    let config = IfacConfig::new(Some(&vectors.ifac_netname_only.netname), None, 16).unwrap();

    // The identity should be deterministic based on inputs
    // We can't directly compare ifac_key since it's private,
    // but we can verify the identity hash is consistent
    let config2 = IfacConfig::new(Some(&vectors.ifac_netname_only.netname), None, 16).unwrap();

    assert_eq!(
        config.identity().hash(),
        config2.identity().hash(),
        "IFAC key derivation should be deterministic"
    );
}

#[test]
fn test_ifac_masking_matches_python() {
    let vectors = load_all_vectors();

    let config = IfacConfig::new(
        Some(&vectors.ifac.netname),
        Some(&vectors.ifac.netkey),
        vectors.ifac.ifac_size,
    )
    .unwrap();

    let test_packet = hex::decode(&vectors.ifac.test_packet).unwrap();
    let expected_masked = hex::decode(&vectors.ifac.masked_packet).unwrap();

    let masked = config.apply_ifac(&test_packet).unwrap();

    assert_eq!(
        hex::encode(&masked),
        hex::encode(&expected_masked),
        "IFAC masking mismatch\nExpected: {}\nGot:      {}",
        hex::encode(&expected_masked),
        hex::encode(&masked)
    );
}

#[test]
fn test_ifac_verification_matches_python() {
    let vectors = load_all_vectors();

    let config = IfacConfig::new(
        Some(&vectors.ifac.netname),
        Some(&vectors.ifac.netkey),
        vectors.ifac.ifac_size,
    )
    .unwrap();

    let masked_packet = hex::decode(&vectors.ifac.masked_packet).unwrap();
    let expected_clean = hex::decode(&vectors.ifac.test_packet).unwrap();

    let clean = config.verify_ifac(&masked_packet).unwrap();

    assert_eq!(
        hex::encode(&clean),
        hex::encode(&expected_clean),
        "IFAC verification mismatch\nExpected: {}\nGot:      {}",
        hex::encode(&expected_clean),
        hex::encode(&clean)
    );
}

#[test]
fn test_ifac_roundtrip_with_python_vectors() {
    let vectors = load_all_vectors();

    let config = IfacConfig::new(
        Some(&vectors.ifac.netname),
        Some(&vectors.ifac.netkey),
        vectors.ifac.ifac_size,
    )
    .unwrap();

    let test_packet = hex::decode(&vectors.ifac.test_packet).unwrap();

    // Apply IFAC
    let masked = config.apply_ifac(&test_packet).unwrap();

    // Verify and unmask
    let clean = config.verify_ifac(&masked).unwrap();

    assert_eq!(clean, test_packet, "IFAC roundtrip failed");
}
