[toolchain]
channel = "stable"
targets = [
    "thumbv7em-none-eabihf", # nRF52840 (ARM Cortex-M4F)
    "thumbv6m-none-eabi",    # RP2040 (ARM Cortex-M0+)
]
# Xtensa targets (ESP32, ESP32-S3) require espup, not rustup.
