[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "tools/uf2-runner.sh"

[target.thumbv7em-none-eabihf]
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"
