#!/usr/bin/env python3
"""Generate BZ2 compression test vectors for Rust verification.

This script generates test vectors using Python's bz2 module that can be used
to verify the Rust implementation produces compatible output.

Usage:
    python scripts/generate_bz2_vectors.py > tests/vectors/bz2_vectors.json
"""

import bz2
import json
import random
import sys


def generate_vectors():
    """Generate a list of test vectors with various data patterns."""
    vectors = []

    # Test case 1: Simple ASCII text
    data = b"Hello, World!"
    vectors.append({
        "name": "simple_ascii",
        "description": "Simple ASCII text",
        "uncompressed_hex": data.hex(),
        "compressed_hex": bz2.compress(data).hex(),
    })

    # Test case 2: Highly compressible (repeated character)
    data = b"A" * 1000
    vectors.append({
        "name": "repeated_char_1000",
        "description": "1000 repeated 'A' characters",
        "uncompressed_hex": data.hex(),
        "compressed_hex": bz2.compress(data).hex(),
    })

    # Test case 3: All byte values
    data = bytes(range(256))
    vectors.append({
        "name": "all_byte_values",
        "description": "All 256 byte values",
        "uncompressed_hex": data.hex(),
        "compressed_hex": bz2.compress(data).hex(),
    })

    # Test case 4: Null bytes
    data = b"\x00" * 100
    vectors.append({
        "name": "null_bytes_100",
        "description": "100 null bytes",
        "uncompressed_hex": data.hex(),
        "compressed_hex": bz2.compress(data).hex(),
    })

    # Test case 5: Binary data with pattern
    data = bytes([i % 256 for i in range(500)])
    vectors.append({
        "name": "pattern_500",
        "description": "500 bytes with repeating 0-255 pattern",
        "uncompressed_hex": data.hex(),
        "compressed_hex": bz2.compress(data).hex(),
    })

    # Test case 6: Small data (edge case)
    data = b"x"
    vectors.append({
        "name": "single_byte",
        "description": "Single byte",
        "uncompressed_hex": data.hex(),
        "compressed_hex": bz2.compress(data).hex(),
    })

    # Test case 7: Empty data (edge case)
    data = b""
    vectors.append({
        "name": "empty",
        "description": "Empty data",
        "uncompressed_hex": data.hex(),
        "compressed_hex": bz2.compress(data).hex(),
    })

    # Test case 8: Alternating bytes
    data = bytes([0x55, 0xAA] * 250)
    vectors.append({
        "name": "alternating_pattern",
        "description": "Alternating 0x55/0xAA pattern (500 bytes)",
        "uncompressed_hex": data.hex(),
        "compressed_hex": bz2.compress(data).hex(),
    })

    # Test case 9: Text with newlines (typical message)
    data = b"Line 1\nLine 2\nLine 3\nLine 4\nLine 5\n"
    vectors.append({
        "name": "multiline_text",
        "description": "Multi-line text",
        "uncompressed_hex": data.hex(),
        "compressed_hex": bz2.compress(data).hex(),
    })

    # Test case 10: Random-looking but deterministic data
    # Use a fixed seed for reproducibility
    random.seed(42)
    data = bytes(random.randint(0, 255) for _ in range(1000))
    vectors.append({
        "name": "pseudorandom_1000",
        "description": "1000 bytes of pseudorandom data (seed=42)",
        "uncompressed_hex": data.hex(),
        "compressed_hex": bz2.compress(data).hex(),
    })

    # Test case 11: Larger highly compressible data
    data = (b"ABCD" * 1000)
    vectors.append({
        "name": "repeated_pattern_4000",
        "description": "4000 bytes of repeated 'ABCD' pattern",
        "uncompressed_hex": data.hex(),
        "compressed_hex": bz2.compress(data).hex(),
    })

    # Test case 12: JSON-like structure
    data = b'{"key": "value", "number": 42, "array": [1, 2, 3]}'
    vectors.append({
        "name": "json_structure",
        "description": "JSON-like structure",
        "uncompressed_hex": data.hex(),
        "compressed_hex": bz2.compress(data).hex(),
    })

    return vectors


def main():
    """Generate and output test vectors as JSON."""
    vectors = generate_vectors()

    output = {
        "description": "BZ2 compression test vectors generated by Python's bz2 module",
        "generator": "scripts/generate_bz2_vectors.py",
        "note": "These vectors are used to verify Rust compression is compatible with Python",
        "vectors": vectors,
    }

    json.dump(output, sys.stdout, indent=2)
    print()  # Final newline


if __name__ == "__main__":
    main()
